#!/usr/bin/bash

# Get directory of this script as DIR...
#
#  (https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup conda for this shell
#
# https://stackoverflow.com/questions/34534513/calling-conda-source-activate-from-bash-script
#
if [ ! -f "$HOME/miniconda3/bin/conda" ]
then
    echo "Install Miniconda"
    exit 1
fi

eval "$("$HOME/miniconda3/bin/conda" shell.bash hook)"

conda activate "$DIR/env"

python responses.py

python csvImport.py responses.csv

python leaders.py --markdown > docs/index.md

python leaders.py --private --markdown > leaders.md

git add docs/index.md
git commit -a -m 'cronjob'
git push
