#!/usr/bin/bash

#!/bin/bash

# Get directory of this script as DIR...
#
#  (https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup conda for this shell
#
# https://stackoverflow.com/questions/34534513/calling-conda-source-activate-from-bash-script
#
if [ ! -f "$HOME/miniconda3/bin/conda" ]
then
    echo "Install Miniconda"
    exit 1
fi

eval "$("$HOME/miniconda3/bin/conda" shell.bash hook)"

if [ ! -d "$DIR/env" ]
then
    conda create -y -p "$DIR/env" python=3.9 sqlite
    conda activate "$DIR/env"
    "$DIR/env/bin/pip" install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
fi

conda activate "$DIR/env"

if [ ! -f "$DIR/bids.db" ]
then
    python csvImport.py --create
fi

