#!/usr/bin/bash

#!/bin/bash

# Get directory of this script as DIR...
#
#  (https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup conda for this shell
#
# https://stackoverflow.com/questions/34534513/calling-conda-source-activate-from-bash-script
#
if [ ! -f "$HOME/miniconda3/bin/conda" ]
then
    echo "Install Miniconda"
    exit 1
fi

eval "$("$HOME/miniconda3/bin/conda" shell.bash hook)"

if [ ! -d "$DIR/env" ]
then
    conda create -y -p "$DIR/env" python flask
fi

connda activate "$DIR/env"

if [ ! -f "$DIR/bids.db" ]
then
    sqlite3 "$DIR/bids.db" <<END
create table items (
  id 
)
END
fi
